name: Release Go Library

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  call-workflow:
    name: Call Workflow
    uses: nicklasfrahm-dev/.github/.github/workflows/release-go-library.yml@main
    secrets: inherit
    permissions:
      checks: write
      contents: write
      pull-requests: write
      issues: write
